export const msgType = {
    apiError: 'Oops, algo salió mal!',
    loNoEmail: 'Ingrese un correo electrónico.',
    loNoPwd: 'Ingrese una contraseña.',
    loNoUser: 'Ingrese un nombre de usuario.',
    loNoCode: 'Ingrese el código de verificación.',
    loValEmail: 'Correo electrónico invalido.',
    loValPwd: 'Contraseña invalida.',
    loValUser: 'Nombre de usuario invalido.',
    loIdleTime: 'La sesión expiro.',
    loNewToken: 'Oops, sin token!',
    loOKCode: 'Código de verificación enviado, revise su correo.',
    regCpeNoRcpt: 'Seleccione un receptor.',
    regCpeNoEmsr: 'Seleccione un emisor.',
    regCpeNoFecha: 'Seleccione una fecha de inicio y fin.',
    regCpeNoNumOC: 'Ingrese el número de documento.',
}